version: "3.8"

services:
  web:
    depends_on:
      - app
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/certs:/etc/nginx/certs"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src/public:/var/www/html"
  app: &app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "${UID}:${GID}"
    depends_on:
      - database
      - mail
    build:
      context: .
      dockerfile: php/Dockerfile
      target: debug
    volumes:
      - "./src:/var/www/html:rw"
      - "./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini"
      - "./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    working_dir: "/var/www/html"
  database:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - database:/var/lib/mysql
  mail:
    image: axllent/mailpit:v1.14
    volumes:
      - ./mail:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  composer:
    <<: *app
    build:
      context: .
      dockerfile: php/Dockerfile
      target: dependencies
    volumes:
      - "./src:/mnt"
    working_dir: "/mnt"
  npm:
    image: node:current-alpine
    volumes:
      - "./src:/mnt"
    working_dir: "/mnt"
    entrypoint: ["npm"]
  artisan:
    <<: *app
    entrypoint: ["php", "./artisan"]

volumes:
  database:
  mail:
